sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.25"
    - "8.24.0"
excludes:
linkReplacements:
