sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.30"
    - "8.34.0"
excludes:
linkReplacements:
